version: 2.1
orbs:
aws-ecr: circleci/aws-ecr@4.0.1
jobs:
  tests:
    docker:
      - image: 'bayesimpact/circleci'
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run: docker-compose run --rm tests
workflows:
  version: 2.1
  workflow:
    jobs:
      - tests
